const dummyPosts = [
  {
    title: 'Lorem ipsum dolor sit amet',
    imageSrc: 'https://via.placeholder.com/150',
    postedBy: 'JohnDoe',
    userPic: '/path/to/john-doe-pic.png',
    daysPosted: 2,
    numMessages: 10,
    score: 100,
    subreddit: 'r/example',
  },
  {
    title: 'Consectetur adipiscing elit',
    imageSrc: 'https://via.placeholder.com/150',
    postedBy: 'JaneDoe',
    userPic: '/path/to/jane-doe-pic.png',
    daysPosted: 5,
    numMessages: 20,
    score: 200,
    subreddit: 'r/example',
  },
  {
    title: 'Sed do eiusmod tempor incididunt',
    imageSrc: 'https://via.placeholder.com/150',
    postedBy: 'Alice',
    userPic: '/path/to/alice-pic.png',
    daysPosted: 1,
    numMessages: 15,
    score: 150,
    subreddit: 'r/example',
  },
  {
    title: 'Ut labore et dolore magna aliqua',
    imageSrc: 'https://via.placeholder.com/150',
    postedBy: 'Bob',
    userPic: '/path/to/bob-pic.png',
    daysPosted: 3,
    numMessages: 8,
    score: 80,
    subreddit: 'r/example',
  },
  {
    title: 'Quis nostrud exercitation ullamco',
    imageSrc: 'https://via.placeholder.com/150',
    postedBy: 'Eve',
    userPic: '/path/to/eve-pic.png',
    daysPosted: 7,
    numMessages: 25,
    score: 250,
    subreddit: 'r/example',
  },
  {
    title: 'Duis aute irure dolor in reprehenderit',
    imageSrc: 'https://via.placeholder.com/150',
    postedBy: 'Charlie',
    userPic: '/path/to/charlie-pic.png',
    daysPosted: 4,
    numMessages: 12,
    score: 120,
    subreddit: 'r/example',
  },
];

export default dummyPosts;
